version: '3'
services:
  postgres:
    image: postgres:15.3
    user: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mq
      - POSTGRES_USER=frappet
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Bangkok
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -d mq -U frappet"]
      test: ["CMD-SHELL", "pg_isready -h postgres -U frappet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 80s  
    networks:
      mq:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=frappet
      - RABBITMQ_DEFAULT_PASS=password
    ports:
        - 5672:5672
        - 15672:15672 # UI
    networks:
      - mq


  memphis-metadata:
    image: memphisos/memphis-metadata:docker-15.2.0-debian-11-r27
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memphis -p 5005"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mq
#    ports:
#      - '5005:5005'
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
  memphis:
    image: "memphisos/memphis:1.1.1-stable"
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://127.0.0.1:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    # pull_policy: always
    networks:
      - mq
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mq:
    external: true

